# Project information
site_name: 'Kuratoren-Handbuch'
site_description: 'Virtuelle Ausstellungen der Deutschen Digitalen Bibliothek'
site_author: 'Deutsche Digitale Bibliothek, Culture to Go & Grandgeorg Websolutions'

# Copyright
copyright: 'Copyright &copy; 2017 Deutsche Digitale Bibliothek, Culture to Go, Grandgeorg Websolutions'


# Structure
pages:
    - Start: index.md
    - Einleitung: einleitung.md
    - Redaktionelle Empfehlungen: empfehlungen.md
    - A Im Überblick: ueberblick.md
    - B Virtuelle Ausstellungen Erstellen:
      - 1. Das Omeka Backend: backend.md
      - 2. Objekte in Omeka: erstellen.md
      - 3. Die Ausstellung anlegen: ausstellung_anlegen.md
      - 4. Ausstellungsseiten anlegen: seiten_anlegen.md
    - C Anhang: anhang.md


# Theme
theme: readthedocs
theme_dir: themes/readthedocs

# Options
extra:
  logo: 'img/logo.svg'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  # Layout wording
  wording_next: 'vor'
  wording_previous: 'zurück'
  wording_built_with: 'Erstellt mit'
  wording_built_using: 'unter Verwendung eines'
  wording_built_theme: 'Themes'
  wording_theme_by: 'von'

extra_css:
    - css/extra.css

extra_javascript:
    - js/jquery-3.1.1.min.js
    - js/extra.js

use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - sane_lists
  - attr_list
  - custom_span_class
  - figureAltCaption
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
